name: Deploy to Github Releases

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - 'releases/**'

jobs:
  build:
    name: Build
    if: ${{ github.event.pull_request.merged }}
    uses: ./.github/workflows/build.yml
    with:
      skip_tests: true
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Create Github release
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.build.outputs.version_tag }}
          release_name: "${{ needs.build.outputs.version_tag }}: ${{ github.event.pull_request.title }}"
          body: ${{ github.event.pull_request.body }}
          draft: true
          prerelease: false
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-release.outputs.upload_url }}
          asset_path: dist/cf-mendix-buildpack.zip
          asset_name: cf-mendix-buildpack.zip
          asset_content_type: application/zip
